### ISSUE TITLE
Extend command should extend from current date instead of exisiting date when user is already expired

### ISSUE THREAD

**Issue by mahlquistj** [frederikhs/pg_user#2]
When extending a user, 6 months is just added to the users current expiration date.

Instead, it would be nice if it added 6 months to the current date **if** the users is already expired.

**Comment by frederikhs** [comment]
fixed in https://github.com/frederikhs/pg_user/commit/38a2192e83c423ec5acf1f91808571f4b1af656f and  relased with https://github.com/frederikhs/pg_user/releases/tag/v1.0.9
